{{- range .Values.configmaps }}
{{- if .enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-{{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}