{{- range .Values.secrets }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
type: {{ .type }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}